version: '3'

services:
  # MongoDB for GraphQL API
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # MariaDB for REST API
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notion_clone
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./notion-clone-api/database.sql:/docker-entrypoint-initdb.d/database.sql

  # GraphQL Server
  graphql-server:
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/task-management
      - JWT_SECRET=your-secret-key-should-be-long-and-secure
    depends_on:
      - mongodb

  # REST API Server (Notion Clone)
  rest-api:
    build: ./notion-clone-api
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=notion_clone
      - JWT_SECRET=your-secret-key-should-be-long-and-secure
      - API_URL=http://localhost:5001
    depends_on:
      - mariadb

volumes:
  mongodb_data:
  mariadb_data:
